before:
  hooks:
    - go mod download
builds:
  - id: kubectl-prof
    main: ./cmd/cli/main.go
    binary: kubectl-prof
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
    goarm: [ 6, 7 ]
    ldflags: |
      -X github.com/josepdcs/kubectl-prof/internal/cli/version.semver={{ .Tag }}
archives:
  - id: kubectl-prof-archive
    name_template: |
      kubectl-prof_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
      {{- with .Arm -}}
        {{- if (eq . "6") -}}hf
        {{- else -}}v{{- . -}}
        {{- end -}}
      {{- end -}}
    builds:
      - kubectl-prof
    format_overrides:
      - goos: windows
        format: zip
    files: [ "LICENSE", "README.md" ]
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
