# Default pod security policy for restricted mode
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-restricted
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  requiredDropCapabilities:
    - ALL
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: RunAsAny
  volumes:
    - '*'

---
# Pod security policy for privileged mode
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
    - max: 65535
      min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'

# Default role for restricted pod security policy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-default
  namespace: default
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-restricted
    resources:
      - podsecuritypolicies
    verbs:
      - use

# Default role binding for above default role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-default
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts

# Profiling will be (only) enabled for this service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiler
  namespace: default


# Role for privileged mode
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-privileged
  namespace: default
rules:
  - apiGroups:
      - policy
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use

# Here we assign the privileged role to the profiler service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-privileged
subjects:
  - kind: ServiceAccount
    name: profiler
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-privileged